// Generated by https://quicktype.io
export interface Response {
  data: Data;
}

export interface Data {
  User: User;
}

export interface User {
  name: string;
  image: string;
  last_name: string;
  ci: string;
  about: string;
  prefession: string;
  mail: string;
  address: string;
  cellphone: string;
  date_birth: string;
  nationality: string;
  links: Link[];
  skills: Skill[];
  languages: Language[];
  educations: Education[];
  experiences: Experience[];
}

export interface Education {
  title: string;
  entity: string;
  location: string;
  date_end: string;
  date_init: string;
}

export interface Experience {
  title: string;
  entity: string;
  location: string;
  date_end: string;
  date_init: string;
  description?: string;
}

export interface Language {
  name: string;
  level: string;
}

export interface Link {
  name: string;
  link: string;
}

export interface Skill {
  name: string;
}
